### ISSUE TITLE
Scripts DML

### ISSUE THREAD

**Issue by Guichardx2** [daminellis/projeto_banco_doceria#4]
# Descrição

###  Preencher o conteúdo das tabelas
Analisar as tabelas e criar os inserts necessários para cada uma. Mínimo 10 para cada tabela.

## Exemplo
![image](https://github.com/daminellis/projeto_banco_doceria/assets/130867213/8819e9f9-961d-46b7-b3c7-633fbf0cd4bb)

### @Guichardx2 
Tabelas:
- [x] produto
- [x] ingrediente
- [x] un_medida
- [x] produto_ingrediente
- [x] categoria_cardapio

### @M0rona  
Tabelas:
- [x] cliente
- [x] pagamento
- [x] pedido
- [x] tipo_pagamento

**Comment by Guichardx2** [comment]
Já iniciei o preenchimento de dados das tabelas conforme marcado nas tasks. Continuarei amanhã para finalizar e seguir para a próxima issue.

**Comment by Guichardx2** [comment]
Tasks de inserts finalizadas para as tabelas: produto, ingrediente, un_medida, produto_ingrediente e categoria_cardapio.

- [x] produto
- [x] ingrediente
- [x] un_medida
- [x] produto_ingrediente
- [x] categoria_cardapio

**Comment by M0rona** [comment]
Modificado como funciona o relacionamento de cardapio, cat cardapio, agora não existe mais a tabela cardapio, e o produto é ligado diretamente com a cat do cardapio
