### ISSUE TITLE
Documentação e estrutura

### ISSUE THREAD

**Issue by Guichardx2** [daminellis/projeto_banco_doceria#5]
## Descrição
Organizar a estrutura do projeto em suas devidas pastas.

## Exemplo
![image](https://github.com/daminellis/projeto_banco_doceria/assets/130867213/ab43c91e-aeb8-49b6-a231-b96402ad3b0a)

**Comment by Lorrust** [comment]
Organização de arquivos efetuada:

- src
- scripts
- docs

O documento de relatório também foi iniciado, sua finalização agora depende de outras etapas do projeto, incluindo dicionário e DML.
