### ISSUE TITLE
Deploy API

### ISSUE THREAD

**Issue by Guichardx2** [daminellis/projeto_banco_doceria#6]
## Descrição

Dar deploy na API

**Comment by Matheus2037** [comment]
Existe a plataforma Railway, tem um plano gratuito para uso e o funcionamento é simples, no site você inicia um projeto e pode utilizar de um repositório do seu github.
A cada commit feito nesse repositório a railway irá fazer automaticamente um novo deploy, com as atualizações.
Segue o link da plataforma: https://railway.app/

**Comment by Lorrust** [comment]
## API está funcionando
Consegui realizar o "deploy" da API, conectando a aplicação ao banco de dados. Como estamos em um ambiente de desenvolvimento, podemos dizer que a API em si já está funcionando.

![image](https://github.com/daminellis/projeto_banco_doceria/assets/97752019/44e1d76f-4b43-435b-a73e-5d5926213436)

## Novos arquivos
Para conseguir estabelecer a conexão, criei dois novos arquivos em na fonte do projeto:
- **crud.py**
- **schemas.py**

O primeiro é referente aos métodos CRUD; o segundo foi criado para segurar a validação e serialização de dados.

Para rodar a API localmente, digite o comando `uvicorn main:app --reload` dentro do diretório que contém a main, que no caso é `src`. Em seguida, acesse `http://127.0.0.1:8000/docs`, ali pode-se utilizar da documentação provida pelo FastAPI enquanto se interage com o banco de dados.

## Próximas etapas
A fim de garantir a completude do projeto, deve-se concentrar agora no desenvolvimento das funções responsáveis pelo CRUD.
