### ISSUE TITLE
Implementação métodos da API Python

### ISSUE THREAD

**Issue by Guichardx2** [daminellis/projeto_banco_doceria#8]
## Descrição
Criar e relacionar os métodos HTTP com a tabela "Pedido".

### @M0rona  - **GET**
- [x] Criar a estrutura de dados que vai ser enviada nos métodos post e put e que irá retornar no GET.

### @Matheus2037  - **PUT**
- [x] Criar o método put;
- [x] Ao chamar o método passamos o id por rota, para não confundir com o Payload.
- [x] Criar um método antes de salvar para saber qual coluna da linha do item foi modificada.

### @daminellis  - **POST**
- [x] Criar o método que insere dados na tabela  

### @Guichardx2 -- **DELETE**
- [x] Criar o método delete, que passa o id por rota.

**Comment by Matheus2037** [comment]
Analisando a implementação dos métodos, conforme a instrução do professor.
Segue link da conversa com o GPT:  https://chatgpt.com/share/e6f45817-d898-442b-bc77-df7c36acdd79

**OBS:** O assunto em questão está no final da conversa

**Comment by Lorrust** [comment]
## Interação entre banco de dados e API está funcionando
Consegui criar um método _get_ para a tabela produto, que busca os dados de um produto através de seu _id_. Abaixo segue resultado com API rodando localmente (teste efetuado no endereço [http://127.0.0.1:8000/docs](http://127.0.0.1:8000/docs)).

![image](https://github.com/daminellis/projeto_banco_doceria/assets/97752019/97fab4ba-6964-433b-a2e4-47ec8a55a54f)

**Comment by Matheus2037** [comment]
### **Metodo PUT adicionado ao projeto**

**O método update_produto:**

1. Recebe o payload como um objeto ProdutoUpdate, no endereço  **http://127.0.0.1:8000/docs**
2. Digamos que foi passado os seguintes campos pelo Payload:

> {
>     "nome": "Novo Nome do Produto",
>     "preco": 49.99
>   }

3. O CRUD irá verificar os campos presentes no payload, verificando se existem ou não
4. Nesse caso existindo apenas os campos nome e preco.
5. Com base nisso, constrói a query para atualizar apenas nome e preco.
6. Executa a query e retorna o produto atualizado.

![ExemploTeste](https://github.com/daminellis/projeto_banco_doceria/assets/88850653/fc34e003-fdd2-434f-81b6-fd401e187e9c)
![ProvaTeste](https://github.com/daminellis/projeto_banco_doceria/assets/88850653/d56cf358-6d4c-41c7-9684-17470b5e2345)

**Comment by daminellis** [comment]
Método POST criado, está adicionando para a tabela produto , sem problemas

**Comment by Guichardx2** [comment]
Método `DELETE` criado, está verificando se o item da tabela produto está em algum pedido da tabela pedido, se estiver ele não exclui mas caso não esteja, ele exclui.

## Inserindo produto teste
![image](https://github.com/daminellis/projeto_banco_doceria/assets/130867213/dcf56d6e-2f74-4388-8fbd-ca60a0d0a977)
|---|
![image](https://github.com/daminellis/projeto_banco_doceria/assets/130867213/57261228-63da-4031-a645-55f3a7ac7bd3)

## Removendo produto teste
![image](https://github.com/daminellis/projeto_banco_doceria/assets/130867213/24457f14-08d1-4a11-ba66-c7c2a511b753)
|---|
![image](https://github.com/daminellis/projeto_banco_doceria/assets/130867213/c443ee0b-643c-4834-9507-8f5a328bb386)
|---|
![image](https://github.com/daminellis/projeto_banco_doceria/assets/130867213/d3e78cf8-fbb1-4bc5-b3bf-6bf2f8bfcdef)
