### ISSUE TITLE
Dicionário de dados

### ISSUE THREAD

**Issue by Guichardx2** [daminellis/projeto_banco_doceria#9]
## Descrição
Desenvolver os arquivos XLSX e Word

**Comment by Lorrust** [comment]
Iniciado desenvolvimento do relatório em Word. Todos as seções realizadas já foram preenchidas, aguardando agora a finalização dos scripts DML e dicionário de dados.

**Comment by daminellis** [comment]
iniciei o exel com os dados, tabelas todas feitas e conferidas, falta somente os indices...

**Comment by daminellis** [comment]
dicionario de dados acabado e postado!
